### ISSUE TITLE
Link in readme broken

### ISSUE THREAD

**Issue by megatux** [taw/konwert#1]
```
The newest version of the package can be downloaded from
<http://qrczak.home.ml.org/programy/linux/konwert/>.
```
Looks broken link

**Comment by taw** [comment]
Right, so this package has been abandoned by the original author, so I just took Ubuntu copy, applied their patches, and put it online in a way that's compatible with `brew install`.

Basically this package exists only for [this brew formula](https://github.com/taw/homebrew-konwert). I don't mean to develop it here.

If I remember the syntax for custom taps correctly, you can install it with `brew install --HEAD taw/konwert/konwert`.
